### ISSUE TITLE
不能识别GMSSL证书,签名与验证不能与gmssl c版本互通

### ISSUE THREAD

**Issue by liyunde** [zhuobie/smcrypto#1]
0. 仅使用库内生成的密钥对可以正常工作
1.使用gmssl生成的sm2证书不能加载
2.openssl ec 格式证书可以加载，签名结果与openssl 和gmssl 不一致，也不能通过对方地签名验证
3.与java版本签名，验证也不相同

**Comment by zhuobie** [comment]
> 1.使用gmssl生成的sm2证书不能加载
> 2.openssl ec 格式证书可以加载，签名结果与openssl 和gmssl 不一致，也不能通过对方地签名验证
> 3.与java版本签名，验证也不相同

我会测试并修复问题，感谢反馈！[https://github.com/duanhongyi/gmssl/issues/40](https://github.com/duanhongyi/gmssl/issues/40)
