### ISSUE TITLE
sm实例创建同时需要公私钥，但有时候只有其中一个

### ISSUE THREAD

**Issue by liyunde** [zhuobie/smcrypto#2]
sm2::CryptSM2::new(&private_key, &public_key, 1);
有时并没有完全有证书对，可能只有其中一个

**Comment by zhuobie** [comment]
> sm2::CryptSM2::new(&private_key, &public_key, 1);
> 有时并没有完全有证书对，可能只有其中一个

可以使用sm2::sm2::pk_from_sk从私钥导出公钥

**Comment by liyunde** [comment]
如果是只有公钥，需要验证外部签名，这时没有私钥，就没法实例化

**Comment by zhuobie** [comment]
> 如果是只有公钥，需要验证外部签名，这时没有私钥，就没法实例化

了然，我会修改。
